wget -c https://grasp.nhlbi.nih.gov/downloads/ResultsOctober2016/C4D%20Genetics%20Consortium/c4d_cad_discovery_metaanalysis.zip
unzip c4d_cad_discovery_metaanalysis.zip 
cp C4D_CAD_DISCOVERY_METAANALYSIS_UPDATE.TXT 21378988_Coronary_artery_disease.txt