wget http://portals.broadinstitute.org/collaboration/giant/images/b/b7/GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt.gz
gzip -cd GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt.gz > GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt
cp GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt 20935630_Body_mass_index.txt