wget -c https://grasp.nhlbi.nih.gov/downloads/ResultsOctober2016/Prokopenko/MAGIC_Prokopenko_InsulinSecretion_data_release_May2014.zip
unzip MAGIC_Prokopenko_InsulinSecretion_data_release_May2014.zip
cp MAGIC_INSULIN_SECRETION_AUCins_AUCgluc_for_release_HMrel27.txt 24699409_Glucose-stimulated_insulin_secretion.txt 